### ISSUE TITLE
Flow stuck/inactive for a user but resumes with random user input

### ISSUE THREAD

**Issue by Tashi-TAP** [glific/glific#3111] opened 2023-09-15 09:50 UTC
**Describe the bug**
The Flow "Akhilesh_tap_sheet_integration_testing" when started for a user starts and then later gets stuck somewhere but it does not terminate or end. There's no user input required or provisioned for in the flow but after a user types in random characters the flow resumes and continues desired action then again gets stuck. This cycle continues.

**To Reproduce**
1. Update your contact field "curr_row_id" to 2
2. Start the flow "Akhilesh_tap_sheet_integration_testing" for yourself 
3. Go to [output sheet](https://docs.google.com/spreadsheets/d/1uxy4YOkI-i4qWHe-Nw5wWM-S9A13qix7-kcFOxbAF1s/edit#gid=0) 
4. See error, error is all the school links are not written as output only one link is written.

**Expected behavior**
The flow should read the school name from this [sheet](https://docs.google.com/spreadsheets/d/11EyPOkXcOWtdDjzQ4wm5BK5xMmQuCSbWBI4Lu5JdRuo/edit#gid=0) and write the generated waba link in the [output sheet](https://docs.google.com/spreadsheets/d/1uxy4YOkI-i4qWHe-Nw5wWM-S9A13qix7-kcFOxbAF1s/edit#gid=0) then the curr_row_id contact field should increment by 1 which is basically the key to read school names then the flow should read the new school name and write the school waba link, this process should continue untill no key is found.
 

**Screenshots**

https://github.com/glific/glific/assets/145113280/ea8f2216-ecc7-4322-9d25-7108468ff4e9

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AkhileshNegi** [comment] 2023-09-20 17:46
Closing this based on the discussion on the [thread](https://discord.com/channels/717975833226248303/1121312266101469254)
The issue is explained in this [message](https://discord.com/channels/717975833226248303/1121312266101469254/1153550613691510947)

**Closed by AkhileshNegi** 2023-09-20 17:46 UTC
Labels: bug
