### ISSUE TITLE
Some messages are not showing the sender name

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1742] opened 2021-09-02 11:19 UTC
**Describe the bug**
Some of the messages in glific are not showing the sender's name

**To Reproduce**
1. Go to colored cow tides account 
2. Search for message `hey akshay, just`
3. Click on the message
4. You will see that there is no username on the message

**Expected behavior**
It should have the user or flow's name

**Screenshots**
![image](https://user-images.githubusercontent.com/32592458/131834516-a2376184-6865-4ad0-bce8-f645e262243b.png)

**Comment by dlobo** [comment] 2021-09-16 17:55
duplicate of #1763

**Closed by dlobo** 2021-09-16 17:55 UTC
Labels: bug, good first issue
