### ISSUE TITLE
For some students the flows didn't trigger when the messaged directly at the number

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#825] opened 2020-12-29 09:34 UTC
**Describe the bug**
Saurabh from TAP reported that some students messaged directly at their number without taking the optin url step. In this case the flows didn't trigger for them.

**To Reproduce**
1. Save a contact to phone or directly message at an org's WA number
2. try to trigger one of their flows
This is happening only when students send a message without clicking the optin link

**Expected behavior**
The flow should be triggered 

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/103274181-13990300-49e7-11eb-956e-65732d960041.png)

**Comment by dlobo** [comment] 2020-12-29 15:52
can we get the phone number of the above account, so we can peek in the DB and see if we are getting the messages. Send us the number on discord (not here)

**Comment by dlobo** [comment] 2020-12-31 02:35
I notice the screenshot its called tab buddy
when I interact with the bot, I don't see tab buddy at all, it might be what they called the contact

**Comment by dlobo** [comment] 2020-12-31 02:46
tried reproducing this on my kids phone. could not reproduce it and it did work. argh

**Comment by pankaj-ag** [comment] 2021-01-04 08:54
We did some testing and could not replicate. 
I am closing this one for now. 
Please reopen in case you see this error again.

**Closed by pankaj-ag** 2021-01-04 08:54 UTC
Labels: help wanted
