### ISSUE TITLE
Flow terminated after template message sent 

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3868] opened 2024-10-30 12:41 UTC
**Describe the bug**
Udhyam has raised this query that for few users the flow was getting terminated after a specific node.

**To Reproduce** (The issue isn't reproducible) Can only update on the images and checking have for few contact ids the NGO shared
1. Go to Udhyam Account
2. Click on Chats >>  Go to these contact id : 2302715, contact id: 5073991, contact id: 2295547
3. Scroll down to chat history the user in this flow- 007_EMC_MP_24-25_Week6_Teacher_Manual the template message 001_mpweek6_manual the user responded to the button `Begin` of the template message but the flow didn't proceed.
There is no continue when there is no response in wait for response 
4. See error (added screenshots below)

**Expected behavior**

**Screenshots**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/49df2bfa-2632-4950-851a-31368b4bd530">
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/09e9a7bc-9dd0-4ffe-a01e-44c412ad82d5">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/a49e6de2-9c04-4ef4-8e91-a47fa6d00a7b">
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/ec69ffa3-6942-49db-96f4-b77105260d07">
<img width="542" alt="image" src="https://github.com/user-attachments/assets/e0116605-c3d6-4c42-afaa-9bb166881e8c">

**Comment by AmishaBisht** [comment] 2024-11-21 07:46
@SangeetaMishr the issue is not replicable, so we are closing it for now. We can reopen it once we have the replication steps or encounter a similar case.

**Closed by AmishaBisht** 2024-11-21 07:46 UTC
