### ISSUE TITLE
Flow not started with the keyword

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2070] opened 2022-02-22 09:36 UTC

**Comment by mohitsharma-22** [comment] 2022-02-22 09:41
User was not able to start a flow with the keyword.
Not able to replicate it at my end.
Issue time 21 Feb @ 13:52 and on 22nd Feb @ 14:19


<img width="821" alt="Screenshot 2022-02-22 at 3 08 02 PM" src="https://user-images.githubusercontent.com/16541548/155105242-cb9ca712-4675-44ce-be6d-1ec7cb730915.png">

<img width="979" alt="Screenshot 2022-02-22 at 3 07 35 PM" src="https://user-images.githubusercontent.com/16541548/155105267-d0ae5b03-ea4e-40e5-91ec-bd85cb491f4c.png">

<img width="1298" alt="Screenshot 2022-02-22 at 3 06 44 PM" src="https://user-images.githubusercontent.com/16541548/155105273-057b4484-0452-4e5e-a199-65bcd3d643eb.png">

**Comment by pankaj-ag** [comment] 2022-02-22 11:04
@mohitsharma-22 need some more time to investigate. I am not able to replicate the issue.

**Comment by pankaj-ag** [comment] 2022-02-23 08:30
@mohitsharma-22 I was able to replicate the issue. 

Root cause: 
The default Gupshup message for optin is on for the mukkarmaar account. From there the opted out button is quite intuitive and when you click on it user gets opted out from the systems. 

Once you opted out and send any message to glific, we search for a flow where the keyword is **optin** and start that for the user. Since there is no flow for mukkmar with that keyword, nothing got triggered for the user. 


Solutions:
1. Disable the default optin message from the gupshup portal. 
2. Add an optin keyword to the flow. We will make it more UI friendly soon. 


References screenshot:
![WhatsApp Image 2022-02-23 at 1 55 06 PM](https://user-images.githubusercontent.com/10670690/155283811-85949635-ad11-4292-84ed-344792ce7400.jpeg)

------------------------

![WhatsApp Image 2022-02-23 at 1 54 45 PM](https://user-images.githubusercontent.com/10670690/155283793-4ecfdf51-fbb8-4220-ba12-38c58fb0ff40.jpeg)

-------------------------

<img width="1440" alt="Screenshot 2022-02-23 at 1 58 06 PM" src="https://user-images.githubusercontent.com/10670690/155284056-184beff9-9f07-4fa4-93b5-b69083c7d8c2.png">

**Comment by pankaj-ag** [comment] 2022-02-23 09:41
I have created another issue to handle things better. Closing this one now. Please re open in case you need further assistance .

**Closed by pankaj-ag** 2022-02-23 09:41 UTC
